# Generated by Django 5.2.7 on 2025-10-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task'),
        ),
    ]
