name: CI - Django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-django black isort flake8
      - name: Lint (flake8)
        run: flake8 .
      - name: Format check (black)
        run: black --check .
      - name: Import order (isort)
        run: isort . --check-only
      - name: Migrate
        run: |
          if [ -f manage.py ]; then python manage.py migrate; fi
      - name: Tests
        run: |
          if [ -f manage.py ]; then pytest -q; fi
